apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager
  label:
    app.kubernetes.io/name: manager
    app.kubernetes.io/version: '0.0.1'
spec:
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      initContainers:
        - name: db-migrate
          image: backend
          command: ["python", "manage.py"]
          args: ["migrate"]
      containers:
        - name: backend
          image: backend
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - name: http
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /api/
              port: http
          readinessProbe:
            httpGet:
              path: /api/
              port: http
          startupProbe:
            httpGet:
              path: /api/
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: manager
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/version: '0.0.1'
spec:
  selector:
    app: manager
  ports:
  - port: 80
    name: http
    targetPort: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manager
  labels:
    app.kubernetes.io/name: manager
    app.kubernetes.io/version: '0.0.1'
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: manager
            port: 
              name: http
---
apiVersion: v1
kind: Secret
metadata:
  name: manager-db
type: Opaque
stringData:
  superUserPassword: postgresSuperUserPsw
  replicationUserPassword: postgresReplicaPsw
---
apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: manager-db
spec:
   replicas: 3
   image: postgres:14.1-alpine
   database:
      size: 200Mi
   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: manager-db
              key: superUserPassword
      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: manager-db
              key: replicationUserPassword
