name: Integration

on:
  - push
  - pull_request

jobs:
  integration:
    name: Integration
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pypoetry
        key: ${{ runner.os }}-${{ hashFiles('poetry.lock') }}
        restore-keys: ${{ runner.os }}

    - name: Install dependencies
      env:
        POETRY_VIRTUALENVS_CREATE: false
      run: >
        pip3 install poetry
        && cd backend
        && poetry install

    - name: Format
      run: >
        black --check backend/manager

    - name: Test
      env:
        DB: sqlite
      run: >
        cd backend/manager
        python manage.py test
